// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SidecarClient is the client API for Sidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SidecarClient interface {
	Register(ctx context.Context, in *RegistrationMsg, opts ...grpc.CallOption) (*RegistrationMsgResponse, error)
	Sub(ctx context.Context, in *SubMsg, opts ...grpc.CallOption) (*SubMsgResponse, error)
	DocUploadStream(ctx context.Context, opts ...grpc.CallOption) (Sidecar_DocUploadStreamClient, error)
	Recv(ctx context.Context, in *Receive, opts ...grpc.CallOption) (*SubTopicResponse, error)
	RecvJS(ctx context.Context, in *ReceiveJS, opts ...grpc.CallOption) (*SubJSTopicResponse, error)
	Unsub(ctx context.Context, in *UnsubMsg, opts ...grpc.CallOption) (*UnsubMsgResponse, error)
	UnsubJS(ctx context.Context, in *UnsubJSMsg, opts ...grpc.CallOption) (*UnsubJSMsgResponse, error)
	Pub(ctx context.Context, in *PubMsg, opts ...grpc.CallOption) (*PubMsgResponse, error)
	PubJS(ctx context.Context, in *PubJSMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Log(ctx context.Context, in *LogMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddJS(ctx context.Context, in *AddJSMsg, opts ...grpc.CallOption) (*AddJSMsgResponse, error)
}

type sidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarClient(cc grpc.ClientConnInterface) SidecarClient {
	return &sidecarClient{cc}
}

func (c *sidecarClient) Register(ctx context.Context, in *RegistrationMsg, opts ...grpc.CallOption) (*RegistrationMsgResponse, error) {
	out := new(RegistrationMsgResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) Sub(ctx context.Context, in *SubMsg, opts ...grpc.CallOption) (*SubMsgResponse, error) {
	out := new(SubMsgResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/Sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) DocUploadStream(ctx context.Context, opts ...grpc.CallOption) (Sidecar_DocUploadStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Sidecar_ServiceDesc.Streams[0], "/messages.Sidecar/DocUploadStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sidecarDocUploadStreamClient{stream}
	return x, nil
}

type Sidecar_DocUploadStreamClient interface {
	Send(*DocUpload) error
	Recv() (*DocUploadResponse, error)
	grpc.ClientStream
}

type sidecarDocUploadStreamClient struct {
	grpc.ClientStream
}

func (x *sidecarDocUploadStreamClient) Send(m *DocUpload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sidecarDocUploadStreamClient) Recv() (*DocUploadResponse, error) {
	m := new(DocUploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sidecarClient) Recv(ctx context.Context, in *Receive, opts ...grpc.CallOption) (*SubTopicResponse, error) {
	out := new(SubTopicResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/Recv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) RecvJS(ctx context.Context, in *ReceiveJS, opts ...grpc.CallOption) (*SubJSTopicResponse, error) {
	out := new(SubJSTopicResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/RecvJS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) Unsub(ctx context.Context, in *UnsubMsg, opts ...grpc.CallOption) (*UnsubMsgResponse, error) {
	out := new(UnsubMsgResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/Unsub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) UnsubJS(ctx context.Context, in *UnsubJSMsg, opts ...grpc.CallOption) (*UnsubJSMsgResponse, error) {
	out := new(UnsubJSMsgResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/UnsubJS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) Pub(ctx context.Context, in *PubMsg, opts ...grpc.CallOption) (*PubMsgResponse, error) {
	out := new(PubMsgResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/Pub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) PubJS(ctx context.Context, in *PubJSMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/PubJS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) Log(ctx context.Context, in *LogMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarClient) AddJS(ctx context.Context, in *AddJSMsg, opts ...grpc.CallOption) (*AddJSMsgResponse, error) {
	out := new(AddJSMsgResponse)
	err := c.cc.Invoke(ctx, "/messages.Sidecar/AddJS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarServer is the server API for Sidecar service.
// All implementations must embed UnimplementedSidecarServer
// for forward compatibility
type SidecarServer interface {
	Register(context.Context, *RegistrationMsg) (*RegistrationMsgResponse, error)
	Sub(context.Context, *SubMsg) (*SubMsgResponse, error)
	DocUploadStream(Sidecar_DocUploadStreamServer) error
	Recv(context.Context, *Receive) (*SubTopicResponse, error)
	RecvJS(context.Context, *ReceiveJS) (*SubJSTopicResponse, error)
	Unsub(context.Context, *UnsubMsg) (*UnsubMsgResponse, error)
	UnsubJS(context.Context, *UnsubJSMsg) (*UnsubJSMsgResponse, error)
	Pub(context.Context, *PubMsg) (*PubMsgResponse, error)
	PubJS(context.Context, *PubJSMsg) (*emptypb.Empty, error)
	Log(context.Context, *LogMsg) (*emptypb.Empty, error)
	AddJS(context.Context, *AddJSMsg) (*AddJSMsgResponse, error)
	mustEmbedUnimplementedSidecarServer()
}

// UnimplementedSidecarServer must be embedded to have forward compatible implementations.
type UnimplementedSidecarServer struct {
}

func (UnimplementedSidecarServer) Register(context.Context, *RegistrationMsg) (*RegistrationMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSidecarServer) Sub(context.Context, *SubMsg) (*SubMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedSidecarServer) DocUploadStream(Sidecar_DocUploadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DocUploadStream not implemented")
}
func (UnimplementedSidecarServer) Recv(context.Context, *Receive) (*SubTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recv not implemented")
}
func (UnimplementedSidecarServer) RecvJS(context.Context, *ReceiveJS) (*SubJSTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecvJS not implemented")
}
func (UnimplementedSidecarServer) Unsub(context.Context, *UnsubMsg) (*UnsubMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsub not implemented")
}
func (UnimplementedSidecarServer) UnsubJS(context.Context, *UnsubJSMsg) (*UnsubJSMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsubJS not implemented")
}
func (UnimplementedSidecarServer) Pub(context.Context, *PubMsg) (*PubMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pub not implemented")
}
func (UnimplementedSidecarServer) PubJS(context.Context, *PubJSMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PubJS not implemented")
}
func (UnimplementedSidecarServer) Log(context.Context, *LogMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedSidecarServer) AddJS(context.Context, *AddJSMsg) (*AddJSMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJS not implemented")
}
func (UnimplementedSidecarServer) mustEmbedUnimplementedSidecarServer() {}

// UnsafeSidecarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarServer will
// result in compilation errors.
type UnsafeSidecarServer interface {
	mustEmbedUnimplementedSidecarServer()
}

func RegisterSidecarServer(s grpc.ServiceRegistrar, srv SidecarServer) {
	s.RegisterService(&Sidecar_ServiceDesc, srv)
}

func _Sidecar_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).Register(ctx, req.(*RegistrationMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).Sub(ctx, req.(*SubMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_DocUploadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SidecarServer).DocUploadStream(&sidecarDocUploadStreamServer{stream})
}

type Sidecar_DocUploadStreamServer interface {
	Send(*DocUploadResponse) error
	Recv() (*DocUpload, error)
	grpc.ServerStream
}

type sidecarDocUploadStreamServer struct {
	grpc.ServerStream
}

func (x *sidecarDocUploadStreamServer) Send(m *DocUploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sidecarDocUploadStreamServer) Recv() (*DocUpload, error) {
	m := new(DocUpload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Sidecar_Recv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Receive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).Recv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/Recv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).Recv(ctx, req.(*Receive))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_RecvJS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveJS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).RecvJS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/RecvJS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).RecvJS(ctx, req.(*ReceiveJS))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_Unsub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).Unsub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/Unsub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).Unsub(ctx, req.(*UnsubMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_UnsubJS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubJSMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).UnsubJS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/UnsubJS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).UnsubJS(ctx, req.(*UnsubJSMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/Pub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).Pub(ctx, req.(*PubMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_PubJS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubJSMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).PubJS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/PubJS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).PubJS(ctx, req.(*PubJSMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).Log(ctx, req.(*LogMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sidecar_AddJS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJSMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServer).AddJS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Sidecar/AddJS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServer).AddJS(ctx, req.(*AddJSMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Sidecar_ServiceDesc is the grpc.ServiceDesc for Sidecar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sidecar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.Sidecar",
	HandlerType: (*SidecarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Sidecar_Register_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _Sidecar_Sub_Handler,
		},
		{
			MethodName: "Recv",
			Handler:    _Sidecar_Recv_Handler,
		},
		{
			MethodName: "RecvJS",
			Handler:    _Sidecar_RecvJS_Handler,
		},
		{
			MethodName: "Unsub",
			Handler:    _Sidecar_Unsub_Handler,
		},
		{
			MethodName: "UnsubJS",
			Handler:    _Sidecar_UnsubJS_Handler,
		},
		{
			MethodName: "Pub",
			Handler:    _Sidecar_Pub_Handler,
		},
		{
			MethodName: "PubJS",
			Handler:    _Sidecar_PubJS_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _Sidecar_Log_Handler,
		},
		{
			MethodName: "AddJS",
			Handler:    _Sidecar_AddJS_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DocUploadStream",
			Handler:       _Sidecar_DocUploadStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/v1/messages/sidecar.proto",
}
