// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: protos/v1/messages/sidecar.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_TYPE_REG           MsgType = 0
	MsgType_MSG_TYPE_REG_RSP       MsgType = 1
	MsgType_MSG_TYPE_LOG           MsgType = 2
	MsgType_MSG_TYPE_LOG_RSP       MsgType = 3
	MsgType_MSG_TYPE_PUB           MsgType = 4
	MsgType_MSG_TYPE_PUB_RSP       MsgType = 5
	MsgType_MSG_TYPE_SUB           MsgType = 6
	MsgType_MSG_TYPE_SUB_RSP       MsgType = 7
	MsgType_MSG_TYPE_SUB_TOPIC_RSP MsgType = 8
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_REG",
		1: "MSG_TYPE_REG_RSP",
		2: "MSG_TYPE_LOG",
		3: "MSG_TYPE_LOG_RSP",
		4: "MSG_TYPE_PUB",
		5: "MSG_TYPE_PUB_RSP",
		6: "MSG_TYPE_SUB",
		7: "MSG_TYPE_SUB_RSP",
		8: "MSG_TYPE_SUB_TOPIC_RSP",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_REG":           0,
		"MSG_TYPE_REG_RSP":       1,
		"MSG_TYPE_LOG":           2,
		"MSG_TYPE_LOG_RSP":       3,
		"MSG_TYPE_PUB":           4,
		"MSG_TYPE_PUB_RSP":       5,
		"MSG_TYPE_SUB":           6,
		"MSG_TYPE_SUB_RSP":       7,
		"MSG_TYPE_SUB_TOPIC_RSP": 8,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_messages_sidecar_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_protos_v1_messages_sidecar_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_OK                Status = 0
	Status_ERR_SENDING_MSG   Status = 1
	Status_ERR_RECEIVING_MSG Status = 2
	Status_ERR_SUBSCRIBING   Status = 3
	Status_ERR_PUBLISHING    Status = 4
	Status_ERR_LOGGING       Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERR_SENDING_MSG",
		2: "ERR_RECEIVING_MSG",
		3: "ERR_SUBSCRIBING",
		4: "ERR_PUBLISHING",
		5: "ERR_LOGGING",
	}
	Status_value = map[string]int32{
		"OK":                0,
		"ERR_SENDING_MSG":   1,
		"ERR_RECEIVING_MSG": 2,
		"ERR_SUBSCRIBING":   3,
		"ERR_PUBLISHING":    4,
		"ERR_LOGGING":       5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_messages_sidecar_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_v1_messages_sidecar_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{1}
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType     MsgType `protobuf:"varint,1,opt,name=msgType,proto3,enum=messages.MsgType" json:"msgType,omitempty"`
	SrcServType string  `protobuf:"bytes,2,opt,name=srcServType,proto3" json:"srcServType,omitempty"`
	DstServType string  `protobuf:"bytes,3,opt,name=dstServType,proto3" json:"dstServType,omitempty"`
	ServId      []byte  `protobuf:"bytes,4,opt,name=servId,proto3" json:"servId,omitempty"`
	MsgId       uint32  `protobuf:"varint,5,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TYPE_REG
}

func (x *Header) GetSrcServType() string {
	if x != nil {
		return x.SrcServType
	}
	return ""
}

func (x *Header) GetDstServType() string {
	if x != nil {
		return x.DstServType
	}
	return ""
}

func (x *Header) GetServId() []byte {
	if x != nil {
		return x.ServId
	}
	return nil
}

func (x *Header) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type ResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHeader) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{2}
}

type RegistrationMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header                  *Header              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ServiceName             string               `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	CircuitFailureThreshold *uint32              `protobuf:"varint,3,opt,name=circuitFailureThreshold,proto3,oneof" json:"circuitFailureThreshold,omitempty"`
	DebounceDelay           *durationpb.Duration `protobuf:"bytes,4,opt,name=debounceDelay,proto3,oneof" json:"debounceDelay,omitempty"`
	RetryNum                *uint32              `protobuf:"varint,5,opt,name=retryNum,proto3,oneof" json:"retryNum,omitempty"`
	RetryDelay              *durationpb.Duration `protobuf:"bytes,6,opt,name=retryDelay,proto3,oneof" json:"retryDelay,omitempty"`
}

func (x *RegistrationMsg) Reset() {
	*x = RegistrationMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationMsg) ProtoMessage() {}

func (x *RegistrationMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationMsg.ProtoReflect.Descriptor instead.
func (*RegistrationMsg) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationMsg) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegistrationMsg) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegistrationMsg) GetCircuitFailureThreshold() uint32 {
	if x != nil && x.CircuitFailureThreshold != nil {
		return *x.CircuitFailureThreshold
	}
	return 0
}

func (x *RegistrationMsg) GetDebounceDelay() *durationpb.Duration {
	if x != nil {
		return x.DebounceDelay
	}
	return nil
}

func (x *RegistrationMsg) GetRetryNum() uint32 {
	if x != nil && x.RetryNum != nil {
		return *x.RetryNum
	}
	return 0
}

func (x *RegistrationMsg) GetRetryDelay() *durationpb.Duration {
	if x != nil {
		return x.RetryDelay
	}
	return nil
}

type RegistrationMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RspHeader *ResponseHeader `protobuf:"bytes,2,opt,name=rspHeader,proto3" json:"rspHeader,omitempty"`
	Msg       string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RegistrationMsgResponse) Reset() {
	*x = RegistrationMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationMsgResponse) ProtoMessage() {}

func (x *RegistrationMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationMsgResponse.ProtoReflect.Descriptor instead.
func (*RegistrationMsgResponse) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationMsgResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegistrationMsgResponse) GetRspHeader() *ResponseHeader {
	if x != nil {
		return x.RspHeader
	}
	return nil
}

func (x *RegistrationMsgResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Publish the given bytes on the given topic.
type PubMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic  string  `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Msg    []byte  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PubMsg) Reset() {
	*x = PubMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubMsg) ProtoMessage() {}

func (x *PubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubMsg.ProtoReflect.Descriptor instead.
func (*PubMsg) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *PubMsg) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PubMsg) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PubMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PubMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RspHeader *ResponseHeader `protobuf:"bytes,2,opt,name=rspHeader,proto3" json:"rspHeader,omitempty"`
	Msg       string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PubMsgResponse) Reset() {
	*x = PubMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubMsgResponse) ProtoMessage() {}

func (x *PubMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubMsgResponse.ProtoReflect.Descriptor instead.
func (*PubMsgResponse) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *PubMsgResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PubMsgResponse) GetRspHeader() *ResponseHeader {
	if x != nil {
		return x.RspHeader
	}
	return nil
}

func (x *PubMsgResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SubMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic    string  `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ChanSize uint32  `protobuf:"varint,3,opt,name=chanSize,proto3" json:"chanSize,omitempty"`
}

func (x *SubMsg) Reset() {
	*x = SubMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMsg) ProtoMessage() {}

func (x *SubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMsg.ProtoReflect.Descriptor instead.
func (*SubMsg) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *SubMsg) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubMsg) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubMsg) GetChanSize() uint32 {
	if x != nil {
		return x.ChanSize
	}
	return 0
}

type SubMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RspHeader *ResponseHeader `protobuf:"bytes,2,opt,name=rspHeader,proto3" json:"rspHeader,omitempty"`
	Msg       string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SubMsgResponse) Reset() {
	*x = SubMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMsgResponse) ProtoMessage() {}

func (x *SubMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMsgResponse.ProtoReflect.Descriptor instead.
func (*SubMsgResponse) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *SubMsgResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubMsgResponse) GetRspHeader() *ResponseHeader {
	if x != nil {
		return x.RspHeader
	}
	return nil
}

func (x *SubMsgResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Receive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *Receive) Reset() {
	*x = Receive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receive) ProtoMessage() {}

func (x *Receive) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receive.ProtoReflect.Descriptor instead.
func (*Receive) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *Receive) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// Change this to SubTopicMsg. This is the message coming from NATS server
// for the specific topic to which this sidecar has subscribed.
type SubTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic  string  `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Msg    []byte  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SubTopicResponse) Reset() {
	*x = SubTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTopicResponse) ProtoMessage() {}

func (x *SubTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTopicResponse.ProtoReflect.Descriptor instead.
func (*SubTopicResponse) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *SubTopicResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubTopicResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubTopicResponse) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type LogMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Msg    string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LogMsg) Reset() {
	*x = LogMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMsg) ProtoMessage() {}

func (x *LogMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMsg.ProtoReflect.Descriptor instead.
func (*LogMsg) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *LogMsg) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LogMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LogMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RspHeader *ResponseHeader `protobuf:"bytes,2,opt,name=rspHeader,proto3" json:"rspHeader,omitempty"`
	Msg       string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LogMsgResponse) Reset() {
	*x = LogMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_messages_sidecar_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMsgResponse) ProtoMessage() {}

func (x *LogMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_messages_sidecar_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMsgResponse.ProtoReflect.Descriptor instead.
func (*LogMsgResponse) Descriptor() ([]byte, []int) {
	return file_protos_v1_messages_sidecar_proto_rawDescGZIP(), []int{12}
}

func (x *LogMsgResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LogMsgResponse) GetRspHeader() *ResponseHeader {
	if x != nil {
		return x.RspHeader
	}
	return nil
}

func (x *LogMsgResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protos_v1_messages_sidecar_proto protoreflect.FileDescriptor

var file_protos_v1_messages_sidecar_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x72, 0x63, 0x53, 0x65, 0x72, 0x76, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x72, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x8d, 0x03, 0x0a, 0x0f, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x17, 0x63, 0x69, 0x72,
	0x63, 0x75, 0x69, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x17, 0x63, 0x69,
	0x72, 0x63, 0x75, 0x69, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65,
	0x73, 0x68, 0x6f, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x12, 0x44, 0x0a, 0x0d, 0x64, 0x65, 0x62, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x0d, 0x64, 0x65,
	0x62, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1f,
	0x0a, 0x08, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x02, 0x52, 0x08, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12,
	0x3e, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x03,
	0x52, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x88, 0x01, 0x01, 0x42,
	0x1a, 0x0a, 0x18, 0x5f, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x64, 0x65, 0x62, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x8d, 0x01, 0x0a, 0x17, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x36, 0x0a, 0x09, 0x72, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x73,
	0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5a, 0x0a, 0x06, 0x50, 0x75, 0x62,
	0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x36, 0x0a, 0x09, 0x72, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x09, 0x72, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x64, 0x0a, 0x06,
	0x53, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x36, 0x0a, 0x09, 0x72, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x73,
	0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x64, 0x0a, 0x10, 0x53, 0x75,
	0x62, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x44, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x09, 0x72, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x09, 0x72, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0xc5, 0x01,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x5f, 0x52, 0x53, 0x50, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f,
	0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4c, 0x4f, 0x47, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55, 0x42, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55, 0x42, 0x5f, 0x52, 0x53, 0x50, 0x10,
	0x05, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55,
	0x42, 0x10, 0x06, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x55, 0x42, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x07, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x53, 0x47,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f,
	0x52, 0x53, 0x50, 0x10, 0x08, 0x2a, 0x76, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x52, 0x52, 0x5f, 0x53,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x45, 0x52, 0x52, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x53,
	0x47, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x52, 0x52, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43,
	0x52, 0x49, 0x42, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x52, 0x52, 0x5f,
	0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b,
	0x45, 0x52, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x32, 0xa3, 0x02,
	0x0a, 0x07, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x12, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67,
	0x1a, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x1a, 0x18, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x52, 0x65, 0x63, 0x76, 0x12, 0x11,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x03, 0x50, 0x75, 0x62, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x69, 0x72, 0x67, 0x61, 0x64, 0x6b, 0x61, 0x72, 0x69, 0x2f, 0x73,
	0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_v1_messages_sidecar_proto_rawDescOnce sync.Once
	file_protos_v1_messages_sidecar_proto_rawDescData = file_protos_v1_messages_sidecar_proto_rawDesc
)

func file_protos_v1_messages_sidecar_proto_rawDescGZIP() []byte {
	file_protos_v1_messages_sidecar_proto_rawDescOnce.Do(func() {
		file_protos_v1_messages_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v1_messages_sidecar_proto_rawDescData)
	})
	return file_protos_v1_messages_sidecar_proto_rawDescData
}

var file_protos_v1_messages_sidecar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_v1_messages_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_v1_messages_sidecar_proto_goTypes = []interface{}{
	(MsgType)(0),                    // 0: messages.MsgType
	(Status)(0),                     // 1: messages.Status
	(*Header)(nil),                  // 2: messages.Header
	(*ResponseHeader)(nil),          // 3: messages.ResponseHeader
	(*Empty)(nil),                   // 4: messages.Empty
	(*RegistrationMsg)(nil),         // 5: messages.RegistrationMsg
	(*RegistrationMsgResponse)(nil), // 6: messages.RegistrationMsgResponse
	(*PubMsg)(nil),                  // 7: messages.PubMsg
	(*PubMsgResponse)(nil),          // 8: messages.PubMsgResponse
	(*SubMsg)(nil),                  // 9: messages.SubMsg
	(*SubMsgResponse)(nil),          // 10: messages.SubMsgResponse
	(*Receive)(nil),                 // 11: messages.Receive
	(*SubTopicResponse)(nil),        // 12: messages.SubTopicResponse
	(*LogMsg)(nil),                  // 13: messages.LogMsg
	(*LogMsgResponse)(nil),          // 14: messages.LogMsgResponse
	(*durationpb.Duration)(nil),     // 15: google.protobuf.Duration
}
var file_protos_v1_messages_sidecar_proto_depIdxs = []int32{
	0,  // 0: messages.Header.msgType:type_name -> messages.MsgType
	2,  // 1: messages.RegistrationMsg.header:type_name -> messages.Header
	15, // 2: messages.RegistrationMsg.debounceDelay:type_name -> google.protobuf.Duration
	15, // 3: messages.RegistrationMsg.retryDelay:type_name -> google.protobuf.Duration
	2,  // 4: messages.RegistrationMsgResponse.header:type_name -> messages.Header
	3,  // 5: messages.RegistrationMsgResponse.rspHeader:type_name -> messages.ResponseHeader
	2,  // 6: messages.PubMsg.header:type_name -> messages.Header
	2,  // 7: messages.PubMsgResponse.header:type_name -> messages.Header
	3,  // 8: messages.PubMsgResponse.rspHeader:type_name -> messages.ResponseHeader
	2,  // 9: messages.SubMsg.header:type_name -> messages.Header
	2,  // 10: messages.SubMsgResponse.header:type_name -> messages.Header
	3,  // 11: messages.SubMsgResponse.rspHeader:type_name -> messages.ResponseHeader
	2,  // 12: messages.SubTopicResponse.header:type_name -> messages.Header
	2,  // 13: messages.LogMsg.header:type_name -> messages.Header
	2,  // 14: messages.LogMsgResponse.header:type_name -> messages.Header
	3,  // 15: messages.LogMsgResponse.rspHeader:type_name -> messages.ResponseHeader
	5,  // 16: messages.Sidecar.Register:input_type -> messages.RegistrationMsg
	9,  // 17: messages.Sidecar.Sub:input_type -> messages.SubMsg
	11, // 18: messages.Sidecar.Recv:input_type -> messages.Receive
	7,  // 19: messages.Sidecar.Pub:input_type -> messages.PubMsg
	13, // 20: messages.Sidecar.Log:input_type -> messages.LogMsg
	6,  // 21: messages.Sidecar.Register:output_type -> messages.RegistrationMsgResponse
	10, // 22: messages.Sidecar.Sub:output_type -> messages.SubMsgResponse
	12, // 23: messages.Sidecar.Recv:output_type -> messages.SubTopicResponse
	8,  // 24: messages.Sidecar.Pub:output_type -> messages.PubMsgResponse
	14, // 25: messages.Sidecar.Log:output_type -> messages.LogMsgResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_protos_v1_messages_sidecar_proto_init() }
func file_protos_v1_messages_sidecar_proto_init() {
	if File_protos_v1_messages_sidecar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v1_messages_sidecar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_messages_sidecar_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_v1_messages_sidecar_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v1_messages_sidecar_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_v1_messages_sidecar_proto_goTypes,
		DependencyIndexes: file_protos_v1_messages_sidecar_proto_depIdxs,
		EnumInfos:         file_protos_v1_messages_sidecar_proto_enumTypes,
		MessageInfos:      file_protos_v1_messages_sidecar_proto_msgTypes,
	}.Build()
	File_protos_v1_messages_sidecar_proto = out.File
	file_protos_v1_messages_sidecar_proto_rawDesc = nil
	file_protos_v1_messages_sidecar_proto_goTypes = nil
	file_protos_v1_messages_sidecar_proto_depIdxs = nil
}
